# Generated by Django 5.2.8 on 2025-12-11 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('data_dodania', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania')),
                ('aktywna', models.BooleanField(default=True, verbose_name='Aktywna')),
            ],
            options={
                'verbose_name': 'Realizacja',
                'verbose_name_plural': 'Realizacje',
                'ordering': ['-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='ZdjecieRealizacji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='realizacje/', verbose_name='Zdjęcie')),
                ('opis', models.CharField(blank=True, max_length=200, verbose_name='Opis zdjęcia')),
                ('kolejnosc', models.IntegerField(default=0, verbose_name='Kolejność wyświetlania')),
                ('realizacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zdjecia', to='website.realizacja', verbose_name='Realizacja')),
            ],
            options={
                'verbose_name': 'Zdjęcie realizacji',
                'verbose_name_plural': 'Zdjęcia realizacji',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
    ]
