# Generated by Django 5.2.8 on 2025-12-12 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zdjecierealizacji',
            name='realizacja',
        ),
        migrations.AlterModelOptions(
            name='zdjecierealizacji',
            options={'ordering': ['kolejnosc', '-data_dodania'], 'verbose_name': 'Zdjęcie realizacji', 'verbose_name_plural': 'Zdjęcia realizacji'},
        ),
        migrations.RemoveField(
            model_name='zdjecierealizacji',
            name='opis',
        ),
        migrations.AddField(
            model_name='zdjecierealizacji',
            name='aktywna',
            field=models.BooleanField(default=True, verbose_name='Aktywna'),
        ),
        migrations.AddField(
            model_name='zdjecierealizacji',
            name='data_dodania',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania'),
        ),
        migrations.AddField(
            model_name='zdjecierealizacji',
            name='tytul',
            field=models.CharField(default='Zdjęcie', max_length=200, verbose_name='Tytuł zdjęcia'),
        ),
        migrations.DeleteModel(
            name='Realizacja',
        ),
    ]
