# Generated by Django 5.2.8 on 2025-12-12 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_zdjecierealizacji_realizacja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tresc', models.TextField(verbose_name='Treść wiadomości')),
                ('data_wyslania', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data wysłania')),
                ('przeczytane', models.BooleanField(default=False, verbose_name='Przeczytane')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
            ],
            options={
                'verbose_name': 'Wiadomość kontaktowa',
                'verbose_name_plural': 'Wiadomości kontaktowe',
                'ordering': ['-data_wyslania'],
            },
        ),
    ]
